language: ruby
cache: bundler
rvm:
  - 2.3.0
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: 75c20eb2ee124a799e77cf252096953caae4939a7c07c52a549ad93f4ff54367
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml config/database_original.yml
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
after_script:
  - cp config/database_original.yml config/database.yml
